# Generated by Django 5.1.6 on 2025-02-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_App', '0002_rename_user_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='division',
            new_name='name',
        ),
    ]
